### ISSUE TITLE
v1.1.0

### ISSUE THREAD

**Issue by seb-sykio** [pwa-builder/ManifoldJS#285]
on your website , i see we can donwload version 1.1.0,
but here I can see 0.7.5
how to get last version ?
I succeeded to build an app, but I can t make apk. Android studio tell me version of gradle is to old 
Error:Failed to complete Gradle execution.

Cause:
The version of Gradle you are using (2.2) does not support the forTasks() method on BuildActionExecuter. Support for this is available in Gradle 3.5 and all later versions.

and when I run command
pwabuilder package -p android -l debug
[debug] pid:9269    : Error: Android SDK not found. Make sure that it is installed. If it is not at the default location, set the ANDROID_HOME environment variable.

but my ANDROID_HOME seems to be set correctly
echo $ANDROID_HOME 
/home/xxx/Android/Sdk

thanks for help

**Comment by boyofgreen** [comment]
Hi @seb-sykio sorry I missed this issue raised in November.  We are in the process of moving away from the cordova plugin and into a straight android package.  In this scenerio above the easiest way of getting it working is to open the project generated in andriod studio and then upgrading the gradle.    Since this is so old, I'm going to close this issue.  If this doesn't help and you still want assistance, please open a new issues and reference this one.
Thanks,
Jeff
